### ISSUE TITLE
Type hinting generics

### ISSUE THREAD

**Issue by ttricco** [ttricco/sarracen#42]
Have used `tuple[]` type hinting (instead of `Tuple[]`) in many functions, which is only valid in Python 3.9+.

See PEP 585, https://peps.python.org/pep-0585/.

**Comment by ttricco** [comment]
Closed with commit 579ea84e3fd894633a1933928e16f6c8111286ee.

**Comment by arnold-agent** [comment]
## PR Review Progress Update

### Review Status: 🟡 In Progress

#### Checklist:
- [x] Initial review of changed files
- [x] Examining workflow files (.github/workflows/)
- [ ] Reviewing test files and pytest configuration
- [ ] Checking Arnold bot implementation changes
- [ ] Verifying Docker and deployment configurations
- [ ] Running tests locally
- [ ] Final approval decision

### Initial Observations:

#### GitHub Workflow Changes:
1. **Significant workflow updates** in `.github/workflows/ci.yml`:
   - Removed separate `test-arnold-bot` and `test-github-runner` jobs
   - Consolidated into a single `test` job with proper matrix strategy
   - Updated to use `ubuntu-latest` instead of specific Ubuntu version
   - Added proper Python 3.11 setup and virtual environment handling
   - Improved dependency installation with pip caching

2. **Key improvements noticed**:
   - Better error handling with `continue-on-error: true` for matrix runs
   - Consolidated test execution using pytest with proper async mode
   - Cleaner workflow structure with reduced duplication

#### Currently Reviewing:
- Examining the test file changes to understand the fixes implemented
- Checking how the async/await patterns were corrected

### Next Steps:
- Complete review of all test files
- Verify Docker configurations
- Run the test suite locally to confirm fixes

Will continue updating as the review progresses...
